// Objective-C API for talking to github.com/willowtreeapps/timestamp Go package.
//   gobind -lang=objc github.com/willowtreeapps/timestamp
//
// File is generated by gobind. Do not edit.

#ifndef __GoTimestamp_H__
#define __GoTimestamp_H__

#include <Foundation/Foundation.h>

@class GoTimestampTimestamp;

@interface GoTimestampTimestamp : NSObject {
}
@property(strong, readonly) id ref;

- (id)initWithRef:(id)ref;
- (int64_t)SecondsSinceEpoch;
- (void)setSecondsSinceEpoch:(int64_t)v;
@end

FOUNDATION_EXPORT BOOL GoTimestampAllJSON(NSData** ret0_, NSError** error);

FOUNDATION_EXPORT BOOL GoTimestampBootstrap(NSError** error);

FOUNDATION_EXPORT BOOL GoTimestampInsert(int64_t seconds, NSError** error);

FOUNDATION_EXPORT BOOL GoTimestampSetUp(NSString* path, NSError** error);

#endif
